# Generated by Django 4.1.7 on 2023-04-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clintapp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/'),
        ),
    ]
